# Generated by Django 4.2.16 on 2026-07-09 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apikeys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyUsageDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_days', to='apikeys.apikey')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'key usage day',
                'verbose_name_plural': 'key usage days',
                'db_table': 'key_usage_days',
                'ordering': ('-date',),
            },
        ),
        migrations.AddConstraint(
            model_name='keyusageday',
            constraint=models.UniqueConstraint(fields=('api_key', 'date'), name='uniq_key_usage_day'),
        ),
    ]
