# Generated by Django 4.2.16 on 2026-07-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikeys', '0002_keyusageday_keyusageday_uniq_key_usage_day'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='keyusageday',
            index=models.Index(fields=['owner', 'date'], name='idx_usage_owner_date'),
        ),
    ]
